version: '3.0'

services:
    php:
        # note you need to manually build this image from base dockerfile above FIRST!
        image: rlukman/base-php-nginx
        dockerfile: base-php.Dockerfile
        build: .
        #volumes:
        #    # used delegated mode here on docker for mac for faster disk I/O
        #    - .:/var/www/app:delegated
        #    - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        #    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        #    - ./nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
              # mount in dev certs if you want to dev over ssl
              #- ./dev-cert.crt:/etc/nginx/ssl/cert.crt
              #- ./dev-key.pem:/etc/nginx/ssl/key.pem
        # entrypoint: /usr/local/bin/docker-php-entrypoint-dev
        # command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
        ports:
            - "8080:80"
            - "8443:443"
            - "9001:9001"
        depends_on:
            - mysql
        environment:
            APP_NAME: SDLT
            APP_ENV: local
            APP_DEBUG: "true"
            APP_KEY: KEYGOESHERE
            APP_LOG: errorlog
            APP_URL: "http://localhost"
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: SDLT
            DB_USERNAME: admin01
            DB_PASSWORD: mypassword01
        networks:
          - RL-SDLT-nw
    mysql:
        image: mysql:5.7
        volumes:
            - mysql:/var/lib/mysql
        ports:
            # we only expose this port in local dev for using mysql tools/guis on your host
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-SDLT}
            MYSQL_USER: ${DB_USERNAME:-admin01}
            MYSQL_PASSWORD: ${DB_PASSWORD:-mypassword01}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysecret}
        networks:
          - RL-SDLT-nw
networks:
    RL-SDLT-nw:
volumes:
  RL-SDLT-data:
  RL-mysql-data:
