version: '3.0'

services:
    base-php:
      build:
        context: .
        dockerfile: base-php.Dockerfile
      image: rlukman/base-php-nginx
    sdlt:
      build:
        context: .
        dockerfile: sdlt.Dockerfile
      image: rlukman/sdlt
      ports:
        - "8080:80"
        - "8443:443"
        - "9001:9001"
      depends_on:
        - mysql
      environment:
        APP_NAME: sdlt
        APP_ENV: local
        APP_DEBUG: "true"
        APP_KEY: KEYGOESHERE
        APP_LOG: errorlog
        APP_URL: "http://localhost"
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: sdlt
        DB_USERNAME: admin01
        DB_PASSWORD: mypassword01
      networks:
        - RLsdltnw
    mysql:
      image: mysql:5.7
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
            # we only expose this port in local dev for using mysql tools/guis on your host
            - "3306:3306"
      environment:
        MYSQL_DATABASE: ${DB_DATABASE:-sdlt}
        MYSQL_USER: ${DB_USERNAME:-admin01}
        MYSQL_PASSWORD: ${DB_PASSWORD:-mypassword01}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysecret01}
      networks:
        - RLsdltnw
networks:
    RLsdltnw:
volumes:
  mysql-data:
